name: my_first_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  flutter_blue_plus: ^1.11.0 # Added for Bluetooth functionality
  firebase_core:    ^3.11.0  # Required if you decide to use Firebase
  cloud_firestore:  ^5.6.3  # To store paired devices if needed
  permission_handler: ^11.0.1 # Required for Bluetooth permissions on Android/iOS
  firebase_auth:  ^5.4.2
  #-----------Safa dependet-------------#
  firebase_database: ^11.3.2 # Adjust if necessary
  fl_chart: ^0.70.2
  intl: ^0.20.2 # Or the latest version
#----------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/back.png
    - assets/blutooth.png
    - assets/editpen.png
    - assets/nasmapatch.png
    - assets/star.png
