name: my_first_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  flutter_blue_plus: ^1.11.0 # Added for Bluetooth functionality
  firebase_core:    ^3.11.0  # Required if you decide to use Firebase
  cloud_firestore:  ^5.6.3  # To store paired devices if needed
  permission_handler: ^11.0.1 # Required for Bluetooth permissions on Android/iOS
  #firebase_auth:  ^5.4.2
  firebase_auth: ^5.1.0
  #-----------Safa dependet-------------#
  firebase_database: ^11.3.2 # Adjust if necessary
  fl_chart: ^0.70.2
  #intl: ^0.20.2 # Or the latest version
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  
#----------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/back.png
    - assets/blutooth.png
    - assets/editpen.png
    - assets/nasmapatch.png
    - assets/star.png
    - assets/background.jpg
    - assets/LOGO.jpg